application: uq-santatracker2017
version: quickdraw
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist_pretty/index.html
  upload: dist_pretty/index.html
  secure: always
  login: admin

- url: /
  static_files: dist_pretty/quickdraw.html
  upload: dist_pretty/quickdraw.html
  secure: always
  login: admin

- url: /(.*)
  static_files: dist_pretty/\1
  upload: dist_pretty/(.*)
  secure: always
  login: admin

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^source$
  - ^node_modules$
  - ^bower_components$
  - ^gulp$
  - ^app$
